<?php
namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountryTableSeeder extends Seeder
{
    public function run(): void
    {
        $countries = [
            [
                "nombre"     => "Afganistán",
                "name"       => "Afghanistan",
                "nom"        => "Afghanistan",
                "iso2"       => "AF",
                "iso3"       => "AFG",
                "phone_code" => "93",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/af.svg",
            ],
            [
                "nombre"     => "Albania",
                "name"       => "Albania",
                "nom"        => "Albanie",
                "iso2"       => "AL",
                "iso3"       => "ALB",
                "phone_code" => "355",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/al.svg",
            ],
            [
                "nombre"     => "Alemania",
                "name"       => "Germany",
                "nom"        => "Allemagne",
                "iso2"       => "DE",
                "iso3"       => "DEU",
                "phone_code" => "49",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/de.svg",
            ],
            [
                "nombre"     => "Algeria",
                "name"       => "Algeria",
                "nom"        => "Algérie",
                "iso2"       => "DZ",
                "iso3"       => "DZA",
                "phone_code" => "213",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/dz.svg",
            ],
            [
                "nombre"     => "Andorra",
                "name"       => "Andorra",
                "nom"        => "Andorra",
                "iso2"       => "AD",
                "iso3"       => "AND",
                "phone_code" => "376",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/ad.svg",
            ],
            [
                "nombre"     => "Angola",
                "name"       => "Angola",
                "nom"        => "Angola",
                "iso2"       => "AO",
                "iso3"       => "AGO",
                "phone_code" => "244",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/ao.svg",
            ],
            [
                "nombre"     => "Anguila",
                "name"       => "Anguilla",
                "nom"        => "Anguilla",
                "iso2"       => "AI",
                "iso3"       => "AIA",
                "phone_code" => "1 264",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/ai.svg",
            ],
            [
                "nombre"     => "Antártida",
                "name"       => "Antarctica",
                "nom"        => "L'Antarctique",
                "iso2"       => "AQ",
                "iso3"       => "ATA",
                "phone_code" => "672",
                "continente" => "Antártida",
                "flag"       => "https://flagcdn.com/aq.svg",
            ],
            [
                "nombre"     => "Antigua y Barbuda",
                "name"       => "Antigua and Barbuda",
                "nom"        => "Antigua et Barbuda",
                "iso2"       => "AG",
                "iso3"       => "ATG",
                "phone_code" => "1 268",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/ag.svg",
            ],
            [
                "nombre"     => "Antillas Neerlandesas",
                "name"       => "Netherlands Antilles",
                "nom"        => "Antilles Néerlandaises",
                "iso2"       => "AN",
                "iso3"       => "ANT",
                "phone_code" => "599",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/an.svg",
            ],
            [
                "nombre"     => "Arabia Saudita",
                "name"       => "Saudi Arabia",
                "nom"        => "Arabie Saoudite",
                "iso2"       => "SA",
                "iso3"       => "SAU",
                "phone_code" => "966",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/sa.svg",
            ],
            [
                "nombre"     => "Argentina",
                "name"       => "Argentina",
                "nom"        => "Argentine",
                "iso2"       => "AR",
                "iso3"       => "ARG",
                "phone_code" => "54",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/ar.svg",
            ],
            [
                "nombre"     => "Armenia",
                "name"       => "Armenia",
                "nom"        => "L'Arménie",
                "iso2"       => "AM",
                "iso3"       => "ARM",
                "phone_code" => "374",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/am.svg",
            ],
            [
                "nombre"     => "Aruba",
                "name"       => "Aruba",
                "nom"        => "Aruba",
                "iso2"       => "AW",
                "iso3"       => "ABW",
                "phone_code" => "297",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/aw.svg",
            ],
            [
                "nombre"     => "Australia",
                "name"       => "Australia",
                "nom"        => "Australie",
                "iso2"       => "AU",
                "iso3"       => "AUS",
                "phone_code" => "61",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/au.svg",
            ],
            [
                "nombre"     => "Austria",
                "name"       => "Austria",
                "nom"        => "Autriche",
                "iso2"       => "AT",
                "iso3"       => "AUT",
                "phone_code" => "43",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/at.svg",
            ],
            [
                "nombre"     => "Azerbayán",
                "name"       => "Azerbaijan",
                "nom"        => "L'Azerbaïdjan",
                "iso2"       => "AZ",
                "iso3"       => "AZE",
                "phone_code" => "994",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/az.svg",
            ],
            [
                "nombre"     => "Bélgica",
                "name"       => "Belgium",
                "nom"        => "Belgique",
                "iso2"       => "BE",
                "iso3"       => "BEL",
                "phone_code" => "32",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/be.svg",
            ],
            [
                "nombre"     => "Bahamas",
                "name"       => "Bahamas",
                "nom"        => "Bahamas",
                "iso2"       => "BS",
                "iso3"       => "BHS",
                "phone_code" => "1 242",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/bs.svg",
            ],
            [
                "nombre"     => "Bahrein",
                "name"       => "Bahrain",
                "nom"        => "Bahreïn",
                "iso2"       => "BH",
                "iso3"       => "BHR",
                "phone_code" => "973",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/bh.svg",
            ],
            [
                "nombre"     => "Bangladesh",
                "name"       => "Bangladesh",
                "nom"        => "Bangladesh",
                "iso2"       => "BD",
                "iso3"       => "BGD",
                "phone_code" => "880",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/bd.svg",
            ],
            [
                "nombre"     => "Barbados",
                "name"       => "Barbados",
                "nom"        => "Barbade",
                "iso2"       => "BB",
                "iso3"       => "BRB",
                "phone_code" => "1 246",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/bb.svg",
            ],
            [
                "nombre"     => "Belice",
                "name"       => "Belize",
                "nom"        => "Belize",
                "iso2"       => "BZ",
                "iso3"       => "BLZ",
                "phone_code" => "501",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/bz.svg",
            ],
            [
                "nombre"     => "Benín",
                "name"       => "Benin",
                "nom"        => "Bénin",
                "iso2"       => "BJ",
                "iso3"       => "BEN",
                "phone_code" => "229",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/bj.svg",
            ],
            [
                "nombre"     => "Bhután",
                "name"       => "Bhutan",
                "nom"        => "Le Bhoutan",
                "iso2"       => "BT",
                "iso3"       => "BTN",
                "phone_code" => "975",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/bt.svg",
            ],
            [
                "nombre"     => "Bielorrusia",
                "name"       => "Belarus",
                "nom"        => "Biélorussie",
                "iso2"       => "BY",
                "iso3"       => "BLR",
                "phone_code" => "375",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/by.svg",
            ],
            [
                "nombre"     => "Birmania",
                "name"       => "Myanmar",
                "nom"        => "Myanmar",
                "iso2"       => "MM",
                "iso3"       => "MMR",
                "phone_code" => "95",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/mm.svg",
            ],
            [
                "nombre"     => "Bolivia",
                "name"       => "Bolivia",
                "nom"        => "Bolivie",
                "iso2"       => "BO",
                "iso3"       => "BOL",
                "phone_code" => "591",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/bo.svg",
            ],
            [
                "nombre"     => "Bosnia y Herzegovina",
                "name"       => "Bosnia and Herzegovina",
                "nom"        => "Bosnie-Herzégovine",
                "iso2"       => "BA",
                "iso3"       => "BIH",
                "phone_code" => "387",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/ba.svg",
            ],
            [
                "nombre"     => "Botsuana",
                "name"       => "Botswana",
                "nom"        => "Botswana",
                "iso2"       => "BW",
                "iso3"       => "BWA",
                "phone_code" => "267",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/bw.svg",
            ],
            [
                "nombre"     => "Brasil",
                "name"       => "Brazil",
                "nom"        => "Brésil",
                "iso2"       => "BR",
                "iso3"       => "BRA",
                "phone_code" => "55",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/br.svg",
            ],
            [
                "nombre"     => "Brunéi",
                "name"       => "Brunei",
                "nom"        => "Brunei",
                "iso2"       => "BN",
                "iso3"       => "BRN",
                "phone_code" => "673",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/bn.svg",
            ],
            [
                "nombre"     => "Bulgaria",
                "name"       => "Bulgaria",
                "nom"        => "Bulgarie",
                "iso2"       => "BG",
                "iso3"       => "BGR",
                "phone_code" => "359",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/bg.svg",
            ],
            [
                "nombre"     => "Burkina Faso",
                "name"       => "Burkina Faso",
                "nom"        => "Burkina Faso",
                "iso2"       => "BF",
                "iso3"       => "BFA",
                "phone_code" => "226",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/bf.svg",
            ],
            [
                "nombre"     => "Burundi",
                "name"       => "Burundi",
                "nom"        => "Burundi",
                "iso2"       => "BI",
                "iso3"       => "BDI",
                "phone_code" => "257",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/bi.svg",
            ],
            [
                "nombre"     => "Cabo Verde",
                "name"       => "Cape Verde",
                "nom"        => "Cap-Vert",
                "iso2"       => "CV",
                "iso3"       => "CPV",
                "phone_code" => "238",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/cv.svg",
            ],
            [
                "nombre"     => "Camboya",
                "name"       => "Cambodia",
                "nom"        => "Cambodge",
                "iso2"       => "KH",
                "iso3"       => "KHM",
                "phone_code" => "855",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/kh.svg",
            ],
            [
                "nombre"     => "Camerún",
                "name"       => "Cameroon",
                "nom"        => "Cameroun",
                "iso2"       => "CM",
                "iso3"       => "CMR",
                "phone_code" => "237",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/cm.svg",
            ],
            [
                "nombre"     => "Canadá",
                "name"       => "Canada",
                "nom"        => "Canada",
                "iso2"       => "CA",
                "iso3"       => "CAN",
                "phone_code" => "1",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/ca.svg",
            ],
            [
                "nombre"     => "Chad",
                "name"       => "Chad",
                "nom"        => "Tchad",
                "iso2"       => "TD",
                "iso3"       => "TCD",
                "phone_code" => "235",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/td.svg",
            ],
            [
                "nombre"     => "Chile",
                "name"       => "Chile",
                "nom"        => "Chili",
                "iso2"       => "CL",
                "iso3"       => "CHL",
                "phone_code" => "56",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/cl.svg",
            ],
            [
                "nombre"     => "China",
                "name"       => "China",
                "nom"        => "Chine",
                "iso2"       => "CN",
                "iso3"       => "CHN",
                "phone_code" => "86",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/cn.svg",
            ],
            [
                "nombre"     => "Chipre",
                "name"       => "Cyprus",
                "nom"        => "Chypre",
                "iso2"       => "CY",
                "iso3"       => "CYP",
                "phone_code" => "357",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/cy.svg",
            ],
            [
                "nombre"     => "Ciudad del Vaticano",
                "name"       => "Vatican City State",
                "nom"        => "Cité du Vatican",
                "iso2"       => "VA",
                "iso3"       => "VAT",
                "phone_code" => "39",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/va.svg",
            ],
            [
                "nombre"     => "Colombia",
                "name"       => "Colombia",
                "nom"        => "Colombie",
                "iso2"       => "CO",
                "iso3"       => "COL",
                "phone_code" => "57",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/co.svg",
            ],
            [
                "nombre"     => "Comoras",
                "name"       => "Comoros",
                "nom"        => "Comores",
                "iso2"       => "KM",
                "iso3"       => "COM",
                "phone_code" => "269",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/km.svg",
            ],
            [
                "nombre"     => "Congo",
                "name"       => "Congo",
                "nom"        => "Congo",
                "iso2"       => "CG",
                "iso3"       => "COG",
                "phone_code" => "242",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/cg.svg",
            ],
            [
                "nombre"     => "Congo",
                "name"       => "Congo",
                "nom"        => "Congo",
                "iso2"       => "CD",
                "iso3"       => "COD",
                "phone_code" => "243",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/cd.svg",
            ],
            [
                "nombre"     => "Corea del Norte",
                "name"       => "North Korea",
                "nom"        => "Corée du Nord",
                "iso2"       => "KP",
                "iso3"       => "PRK",
                "phone_code" => "850",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/kp.svg",
            ],
            [
                "nombre"     => "Corea del Sur",
                "name"       => "South Korea",
                "nom"        => "Corée du Sud",
                "iso2"       => "KR",
                "iso3"       => "KOR",
                "phone_code" => "82",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/kr.svg",
            ],
            [
                "nombre"     => "Costa de Marfil",
                "name"       => "Ivory Coast",
                "nom"        => "Côte-d'Ivoire",
                "iso2"       => "CI",
                "iso3"       => "CIV",
                "phone_code" => "225",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/ci.svg",
            ],
            [
                "nombre"     => "Costa Rica",
                "name"       => "Costa Rica",
                "nom"        => "Costa Rica",
                "iso2"       => "CR",
                "iso3"       => "CRI",
                "phone_code" => "506",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/cr.svg",
            ],
            [
                "nombre"     => "Croacia",
                "name"       => "Croatia",
                "nom"        => "Croatie",
                "iso2"       => "HR",
                "iso3"       => "HRV",
                "phone_code" => "385",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/hr.svg",
            ],
            [
                "nombre"     => "Cuba",
                "name"       => "Cuba",
                "nom"        => "Cuba",
                "iso2"       => "CU",
                "iso3"       => "CUB",
                "phone_code" => "53",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/cu.svg",
            ],
            [
                "nombre"     => "Dinamarca",
                "name"       => "Denmark",
                "nom"        => "Danemark",
                "iso2"       => "DK",
                "iso3"       => "DNK",
                "phone_code" => "45",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/dk.svg",
            ],
            [
                "nombre"     => "Dominica",
                "name"       => "Dominica",
                "nom"        => "Dominique",
                "iso2"       => "DM",
                "iso3"       => "DMA",
                "phone_code" => "1 767",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/dm.svg",
            ],
            [
                "nombre"     => "Ecuador",
                "name"       => "Ecuador",
                "nom"        => "Equateur",
                "iso2"       => "EC",
                "iso3"       => "ECU",
                "phone_code" => "593",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/ec.svg",
            ],
            [
                "nombre"     => "Egipto",
                "name"       => "Egypt",
                "nom"        => "Egypte",
                "iso2"       => "EG",
                "iso3"       => "EGY",
                "phone_code" => "20",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/eg.svg",
            ],
            [
                "nombre"     => "El Salvador",
                "name"       => "El Salvador",
                "nom"        => "El Salvador",
                "iso2"       => "SV",
                "iso3"       => "SLV",
                "phone_code" => "503",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/sv.svg",
            ],
            [
                "nombre"     => "Emiratos Árabes Unidos",
                "name"       => "United Arab Emirates",
                "nom"        => "Emirats Arabes Unis",
                "iso2"       => "AE",
                "iso3"       => "ARE",
                "phone_code" => "971",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/ae.svg",
            ],
            [
                "nombre"     => "Eritrea",
                "name"       => "Eritrea",
                "nom"        => "Erythrée",
                "iso2"       => "ER",
                "iso3"       => "ERI",
                "phone_code" => "291",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/er.svg",
            ],
            [
                "nombre"     => "Eslovaquia",
                "name"       => "Slovakia",
                "nom"        => "Slovaquie",
                "iso2"       => "SK",
                "iso3"       => "SVK",
                "phone_code" => "421",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/sk.svg",
            ],
            [
                "nombre"     => "Eslovenia",
                "name"       => "Slovenia",
                "nom"        => "Slovénie",
                "iso2"       => "SI",
                "iso3"       => "SVN",
                "phone_code" => "386",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/si.svg",
            ],
            [
                "nombre"     => "España",
                "name"       => "Spain",
                "nom"        => "Espagne",
                "iso2"       => "ES",
                "iso3"       => "ESP",
                "phone_code" => "34",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/es.svg",
            ],
            [
                "nombre"     => "Estados Unidos de América",
                "name"       => "United States of America",
                "nom"        => "États-Unis d'Amérique",
                "iso2"       => "US",
                "iso3"       => "USA",
                "phone_code" => "1",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/us.svg",
            ],
            [
                "nombre"     => "Estonia",
                "name"       => "Estonia",
                "nom"        => "L'Estonie",
                "iso2"       => "EE",
                "iso3"       => "EST",
                "phone_code" => "372",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/ee.svg",
            ],
            [
                "nombre"     => "Etiopía",
                "name"       => "Ethiopia",
                "nom"        => "Ethiopie",
                "iso2"       => "ET",
                "iso3"       => "ETH",
                "phone_code" => "251",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/et.svg",
            ],
            [
                "nombre"     => "Filipinas",
                "name"       => "Philippines",
                "nom"        => "Philippines",
                "iso2"       => "PH",
                "iso3"       => "PHL",
                "phone_code" => "63",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/ph.svg",
            ],
            [
                "nombre"     => "Finlandia",
                "name"       => "Finland",
                "nom"        => "Finlande",
                "iso2"       => "FI",
                "iso3"       => "FIN",
                "phone_code" => "358",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/fi.svg",
            ],
            [
                "nombre"     => "Fiyi",
                "name"       => "Fiji",
                "nom"        => "Fidji",
                "iso2"       => "FJ",
                "iso3"       => "FJI",
                "phone_code" => "679",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/fj.svg",
            ],
            [
                "nombre"     => "Francia",
                "name"       => "France",
                "nom"        => "France",
                "iso2"       => "FR",
                "iso3"       => "FRA",
                "phone_code" => "33",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/fr.svg",
            ],
            [
                "nombre"     => "Gabón",
                "name"       => "Gabon",
                "nom"        => "Gabon",
                "iso2"       => "GA",
                "iso3"       => "GAB",
                "phone_code" => "241",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/ga.svg",
            ],
            [
                "nombre"     => "Gambia",
                "name"       => "Gambia",
                "nom"        => "Gambie",
                "iso2"       => "GM",
                "iso3"       => "GMB",
                "phone_code" => "220",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/gm.svg",
            ],
            [
                "nombre"     => "Georgia",
                "name"       => "Georgia",
                "nom"        => "Géorgie",
                "iso2"       => "GE",
                "iso3"       => "GEO",
                "phone_code" => "995",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/ge.svg",
            ],
            [
                "nombre"     => "Ghana",
                "name"       => "Ghana",
                "nom"        => "Ghana",
                "iso2"       => "GH",
                "iso3"       => "GHA",
                "phone_code" => "233",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/gh.svg",
            ],
            [
                "nombre"     => "Gibraltar",
                "name"       => "Gibraltar",
                "nom"        => "Gibraltar",
                "iso2"       => "GI",
                "iso3"       => "GIB",
                "phone_code" => "350",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/gi.svg",
            ],
            [
                "nombre"     => "Granada",
                "name"       => "Grenada",
                "nom"        => "Grenade",
                "iso2"       => "GD",
                "iso3"       => "GRD",
                "phone_code" => "1 473",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/gd.svg",
            ],
            [
                "nombre"     => "Grecia",
                "name"       => "Greece",
                "nom"        => "Grèce",
                "iso2"       => "GR",
                "iso3"       => "GRC",
                "phone_code" => "30",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/gr.svg",
            ],
            [
                "nombre"     => "Groenlandia",
                "name"       => "Greenland",
                "nom"        => "Groenland",
                "iso2"       => "GL",
                "iso3"       => "GRL",
                "phone_code" => "299",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/gl.svg",
            ],
            [
                "nombre"     => "Guadalupe",
                "name"       => "Guadeloupe",
                "nom"        => "Guadeloupe",
                "iso2"       => "GP",
                "iso3"       => "GLP",
                "phone_code" => "",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/gp.svg",
            ],
            [
                "nombre"     => "Guam",
                "name"       => "Guam",
                "nom"        => "Guam",
                "iso2"       => "GU",
                "iso3"       => "GUM",
                "phone_code" => "1 671",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/gu.svg",
            ],
            [
                "nombre"     => "Guatemala",
                "name"       => "Guatemala",
                "nom"        => "Guatemala",
                "iso2"       => "GT",
                "iso3"       => "GTM",
                "phone_code" => "502",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/gt.svg",
            ],
            [
                "nombre"     => "Guayana Francesa",
                "name"       => "French Guiana",
                "nom"        => "Guyane française",
                "iso2"       => "GF",
                "iso3"       => "GUF",
                "phone_code" => "",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/gf.svg",
            ],
            [
                "nombre"     => "Guernsey",
                "name"       => "Guernsey",
                "nom"        => "Guernesey",
                "iso2"       => "GG",
                "iso3"       => "GGY",
                "phone_code" => "",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/gg.svg",
            ],
            [
                "nombre"     => "Guinea",
                "name"       => "Guinea",
                "nom"        => "Guinée",
                "iso2"       => "GN",
                "iso3"       => "GIN",
                "phone_code" => "224",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/gn.svg",
            ],
            [
                "nombre"     => "Guinea Ecuatorial",
                "name"       => "Equatorial Guinea",
                "nom"        => "Guinée Equatoriale",
                "iso2"       => "GQ",
                "iso3"       => "GNQ",
                "phone_code" => "240",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/gq.svg",
            ],
            [
                "nombre"     => "Guinea-Bissau",
                "name"       => "Guinea-Bissau",
                "nom"        => "Guinée-Bissau",
                "iso2"       => "GW",
                "iso3"       => "GNB",
                "phone_code" => "245",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/gw.svg",
            ],
            [
                "nombre"     => "Guyana",
                "name"       => "Guyana",
                "nom"        => "Guyane",
                "iso2"       => "GY",
                "iso3"       => "GUY",
                "phone_code" => "592",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/gy.svg",
            ],
            [
                "nombre"     => "Haití",
                "name"       => "Haiti",
                "nom"        => "Haïti",
                "iso2"       => "HT",
                "iso3"       => "HTI",
                "phone_code" => "509",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/ht.svg",
            ],
            [
                "nombre"     => "Honduras",
                "name"       => "Honduras",
                "nom"        => "Honduras",
                "iso2"       => "HN",
                "iso3"       => "HND",
                "phone_code" => "504",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/hn.svg",
            ],
            [
                "nombre"     => "Hong kong",
                "name"       => "Hong Kong",
                "nom"        => "Hong Kong",
                "iso2"       => "HK",
                "iso3"       => "HKG",
                "phone_code" => "852",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/hk.svg",
            ],
            [
                "nombre"     => "Hungría",
                "name"       => "Hungary",
                "nom"        => "Hongrie",
                "iso2"       => "HU",
                "iso3"       => "HUN",
                "phone_code" => "36",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/hu.svg",
            ],
            [
                "nombre"     => "India",
                "name"       => "India",
                "nom"        => "Inde",
                "iso2"       => "IN",
                "iso3"       => "IND",
                "phone_code" => "91",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/in.svg",
            ],
            [
                "nombre"     => "Indonesia",
                "name"       => "Indonesia",
                "nom"        => "Indonésie",
                "iso2"       => "ID",
                "iso3"       => "IDN",
                "phone_code" => "62",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/id.svg",
            ],
            [
                "nombre"     => "Irán",
                "name"       => "Iran",
                "nom"        => "Iran",
                "iso2"       => "IR",
                "iso3"       => "IRN",
                "phone_code" => "98",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/ir.svg",
            ],
            [
                "nombre"     => "Irak",
                "name"       => "Iraq",
                "nom"        => "Irak",
                "iso2"       => "IQ",
                "iso3"       => "IRQ",
                "phone_code" => "964",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/iq.svg",
            ],
            [
                "nombre"     => "Irlanda",
                "name"       => "Ireland",
                "nom"        => "Irlande",
                "iso2"       => "IE",
                "iso3"       => "IRL",
                "phone_code" => "353",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/ie.svg",
            ],
            [
                "nombre"     => "Isla Bouvet",
                "name"       => "Bouvet Island",
                "nom"        => "Bouvet Island",
                "iso2"       => "BV",
                "iso3"       => "BVT",
                "phone_code" => "",
                "continente" => "Antártida",
                "flag"       => "https://flagcdn.com/bv.svg",
            ],
            [
                "nombre"     => "Isla de Man",
                "name"       => "Isle of Man",
                "nom"        => "Ile de Man",
                "iso2"       => "IM",
                "iso3"       => "IMN",
                "phone_code" => "44",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/im.svg",
            ],
            [
                "nombre"     => "Isla de Navidad",
                "name"       => "Christmas Island",
                "nom"        => "Christmas Island",
                "iso2"       => "CX",
                "iso3"       => "CXR",
                "phone_code" => "61",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/cx.svg",
            ],
            [
                "nombre"     => "Isla Norfolk",
                "name"       => "Norfolk Island",
                "nom"        => "Île de Norfolk",
                "iso2"       => "NF",
                "iso3"       => "NFK",
                "phone_code" => "",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/nf.svg",
            ],
            [
                "nombre"     => "Islandia",
                "name"       => "Iceland",
                "nom"        => "Islande",
                "iso2"       => "IS",
                "iso3"       => "ISL",
                "phone_code" => "354",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/is.svg",
            ],
            [
                "nombre"     => "Islas Bermudas",
                "name"       => "Bermuda Islands",
                "nom"        => "Bermudes",
                "iso2"       => "BM",
                "iso3"       => "BMU",
                "phone_code" => "1 441",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/bm.svg",
            ],
            [
                "nombre"     => "Islas Caimán",
                "name"       => "Cayman Islands",
                "nom"        => "Iles Caïmans",
                "iso2"       => "KY",
                "iso3"       => "CYM",
                "phone_code" => "1 345",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/ky.svg",
            ],
            [
                "nombre"     => "Islas Cocos (Keeling)",
                "name"       => "Cocos (Keeling) Islands",
                "nom"        => "Cocos (Keeling",
                "iso2"       => "CC",
                "iso3"       => "CCK",
                "phone_code" => "61",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/cc.svg",
            ],
            [
                "nombre"     => "Islas Cook",
                "name"       => "Cook Islands",
                "nom"        => "Iles Cook",
                "iso2"       => "CK",
                "iso3"       => "COK",
                "phone_code" => "682",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/ck.svg",
            ],
            [
                "nombre"     => "Islas de Åland",
                "name"       => "Åland Islands",
                "nom"        => "Îles Åland",
                "iso2"       => "AX",
                "iso3"       => "ALA",
                "phone_code" => "",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/ax.svg",
            ],
            [
                "nombre"     => "Islas Feroe",
                "name"       => "Faroe Islands",
                "nom"        => "Iles Féro",
                "iso2"       => "FO",
                "iso3"       => "FRO",
                "phone_code" => "298",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/fo.svg",
            ],
            [
                "nombre"     => "Islas Georgias del Sur y Sandwich del Sur",
                "name"       => "South Georgia and the South Sandwich Islands",
                "nom"        => "Géorgie du Sud et les Îles Sandwich du Sud",
                "iso2"       => "GS",
                "iso3"       => "SGS",
                "phone_code" => "",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/gs.svg",
            ],
            [
                "nombre"     => "Islas Heard y McDonald",
                "name"       => "Heard Island and McDonald Islands",
                "nom"        => "Les îles Heard et McDonald",
                "iso2"       => "HM",
                "iso3"       => "HMD",
                "phone_code" => "",
                "continente" => "Antártida",
                "flag"       => "https://flagcdn.com/hm.svg",
            ],
            [
                "nombre"     => "Islas Maldivas",
                "name"       => "Maldives",
                "nom"        => "Maldives",
                "iso2"       => "MV",
                "iso3"       => "MDV",
                "phone_code" => "960",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/mv.svg",
            ],
            [
                "nombre"     => "Islas Malvinas",
                "name"       => "Falkland Islands (Malvinas)",
                "nom"        => "Iles Falkland (Malvinas",
                "iso2"       => "FK",
                "iso3"       => "FLK",
                "phone_code" => "500",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/fk.svg",
            ],
            [
                "nombre"     => "Islas Marianas del Norte",
                "name"       => "Northern Mariana Islands",
                "nom"        => "Iles Mariannes du Nord",
                "iso2"       => "MP",
                "iso3"       => "MNP",
                "phone_code" => "1 670",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/mp.svg",
            ],
            [
                "nombre"     => "Islas Marshall",
                "name"       => "Marshall Islands",
                "nom"        => "Iles Marshall",
                "iso2"       => "MH",
                "iso3"       => "MHL",
                "phone_code" => "692",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/mh.svg",
            ],
            [
                "nombre"     => "Islas Pitcairn",
                "name"       => "Pitcairn Islands",
                "nom"        => "Iles Pitcairn",
                "iso2"       => "PN",
                "iso3"       => "PCN",
                "phone_code" => "870",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/pn.svg",
            ],
            [
                "nombre"     => "Islas Salomón",
                "name"       => "Solomon Islands",
                "nom"        => "Iles Salomon",
                "iso2"       => "SB",
                "iso3"       => "SLB",
                "phone_code" => "677",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/sb.svg",
            ],
            [
                "nombre"     => "Islas Turcas y Caicos",
                "name"       => "Turks and Caicos Islands",
                "nom"        => "Iles Turques et Caïques",
                "iso2"       => "TC",
                "iso3"       => "TCA",
                "phone_code" => "1 649",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/tc.svg",
            ],
            [
                "nombre"     => "Islas Ultramarinas Menores de Estados Unidos",
                "name"       => "United States Minor Outlying Islands",
                "nom"        => "États-Unis Îles mineures éloignées",
                "iso2"       => "UM",
                "iso3"       => "UMI",
                "phone_code" => "",
                "continente" => "",
                "flag"       => "https://flagcdn.com/um.svg",
            ],
            [
                "nombre"     => "Islas Vírgenes Británicas",
                "name"       => "Virgin Islands",
                "nom"        => "Iles Vierges",
                "iso2"       => "VG",
                "iso3"       => "VG",
                "phone_code" => "1 284",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/vg.svg",
            ],
            [
                "nombre"     => "Islas Vírgenes de los Estados Unidos",
                "name"       => "United States Virgin Islands",
                "nom"        => "Îles Vierges américaines",
                "iso2"       => "VI",
                "iso3"       => "VIR",
                "phone_code" => "1 340",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/vi.svg",
            ],
            [
                "nombre"     => "Israel",
                "name"       => "Israel",
                "nom"        => "Israël",
                "iso2"       => "IL",
                "iso3"       => "ISR",
                "phone_code" => "972",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/il.svg",
            ],
            [
                "nombre"     => "Italia",
                "name"       => "Italy",
                "nom"        => "Italie",
                "iso2"       => "IT",
                "iso3"       => "ITA",
                "phone_code" => "39",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/it.svg",
            ],
            [
                "nombre"     => "Jamaica",
                "name"       => "Jamaica",
                "nom"        => "Jamaïque",
                "iso2"       => "JM",
                "iso3"       => "JAM",
                "phone_code" => "1 876",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/jm.svg",
            ],
            [
                "nombre"     => "Japón",
                "name"       => "Japan",
                "nom"        => "Japon",
                "iso2"       => "JP",
                "iso3"       => "JPN",
                "phone_code" => "81",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/jp.svg",
            ],
            [
                "nombre"     => "Jersey",
                "name"       => "Jersey",
                "nom"        => "Maillot",
                "iso2"       => "JE",
                "iso3"       => "JEY",
                "phone_code" => "",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/je.svg",
            ],
            [
                "nombre"     => "Jordania",
                "name"       => "Jordan",
                "nom"        => "Jordan",
                "iso2"       => "JO",
                "iso3"       => "JOR",
                "phone_code" => "962",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/jo.svg",
            ],
            [
                "nombre"     => "Kazajistán",
                "name"       => "Kazakhstan",
                "nom"        => "Le Kazakhstan",
                "iso2"       => "KZ",
                "iso3"       => "KAZ",
                "phone_code" => "7",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/kz.svg",
            ],
            [
                "nombre"     => "Kenia",
                "name"       => "Kenya",
                "nom"        => "Kenya",
                "iso2"       => "KE",
                "iso3"       => "KEN",
                "phone_code" => "254",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/ke.svg",
            ],
            [
                "nombre"     => "Kirgizstán",
                "name"       => "Kyrgyzstan",
                "nom"        => "Kirghizstan",
                "iso2"       => "KG",
                "iso3"       => "KGZ",
                "phone_code" => "996",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/kg.svg",
            ],
            [
                "nombre"     => "Kiribati",
                "name"       => "Kiribati",
                "nom"        => "Kiribati",
                "iso2"       => "KI",
                "iso3"       => "KIR",
                "phone_code" => "686",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/ki.svg",
            ],
            [
                "nombre"     => "Kuwait",
                "name"       => "Kuwait",
                "nom"        => "Koweït",
                "iso2"       => "KW",
                "iso3"       => "KWT",
                "phone_code" => "965",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/kw.svg",
            ],
            [
                "nombre"     => "Líbano",
                "name"       => "Lebanon",
                "nom"        => "Liban",
                "iso2"       => "LB",
                "iso3"       => "LBN",
                "phone_code" => "961",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/lb.svg",
            ],
            [
                "nombre"     => "Laos",
                "name"       => "Laos",
                "nom"        => "Laos",
                "iso2"       => "LA",
                "iso3"       => "LAO",
                "phone_code" => "856",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/la.svg",
            ],
            [
                "nombre"     => "Lesoto",
                "name"       => "Lesotho",
                "nom"        => "Lesotho",
                "iso2"       => "LS",
                "iso3"       => "LSO",
                "phone_code" => "266",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/ls.svg",
            ],
            [
                "nombre"     => "Letonia",
                "name"       => "Latvia",
                "nom"        => "La Lettonie",
                "iso2"       => "LV",
                "iso3"       => "LVA",
                "phone_code" => "371",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/lv.svg",
            ],
            [
                "nombre"     => "Liberia",
                "name"       => "Liberia",
                "nom"        => "Liberia",
                "iso2"       => "LR",
                "iso3"       => "LBR",
                "phone_code" => "231",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/lr.svg",
            ],
            [
                "nombre"     => "Libia",
                "name"       => "Libya",
                "nom"        => "Libye",
                "iso2"       => "LY",
                "iso3"       => "LBY",
                "phone_code" => "218",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/ly.svg",
            ],
            [
                "nombre"     => "Liechtenstein",
                "name"       => "Liechtenstein",
                "nom"        => "Liechtenstein",
                "iso2"       => "LI",
                "iso3"       => "LIE",
                "phone_code" => "423",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/li.svg",
            ],
            [
                "nombre"     => "Lituania",
                "name"       => "Lithuania",
                "nom"        => "La Lituanie",
                "iso2"       => "LT",
                "iso3"       => "LTU",
                "phone_code" => "370",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/lt.svg",
            ],
            [
                "nombre"     => "Luxemburgo",
                "name"       => "Luxembourg",
                "nom"        => "Luxembourg",
                "iso2"       => "LU",
                "iso3"       => "LUX",
                "phone_code" => "352",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/lu.svg",
            ],
            [
                "nombre"     => "México",
                "name"       => "Mexico",
                "nom"        => "Mexique",
                "iso2"       => "MX",
                "iso3"       => "MEX",
                "phone_code" => "52",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/mx.svg",
            ],
            [
                "nombre"     => "Mónaco",
                "name"       => "Monaco",
                "nom"        => "Monaco",
                "iso2"       => "MC",
                "iso3"       => "MCO",
                "phone_code" => "377",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/mc.svg",
            ],
            [
                "nombre"     => "Macao",
                "name"       => "Macao",
                "nom"        => "Macao",
                "iso2"       => "MO",
                "iso3"       => "MAC",
                "phone_code" => "853",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/mo.svg",
            ],
            [
                "nombre"     => "Macedônia",
                "name"       => "Macedonia",
                "nom"        => "Macédoine",
                "iso2"       => "MK",
                "iso3"       => "MKD",
                "phone_code" => "389",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/mk.svg",
            ],
            [
                "nombre"     => "Madagascar",
                "name"       => "Madagascar",
                "nom"        => "Madagascar",
                "iso2"       => "MG",
                "iso3"       => "MDG",
                "phone_code" => "261",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/mg.svg",
            ],
            [
                "nombre"     => "Malasia",
                "name"       => "Malaysia",
                "nom"        => "Malaisie",
                "iso2"       => "MY",
                "iso3"       => "MYS",
                "phone_code" => "60",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/my.svg",
            ],
            [
                "nombre"     => "Malawi",
                "name"       => "Malawi",
                "nom"        => "Malawi",
                "iso2"       => "MW",
                "iso3"       => "MWI",
                "phone_code" => "265",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/mw.svg",
            ],
            [
                "nombre"     => "Mali",
                "name"       => "Mali",
                "nom"        => "Mali",
                "iso2"       => "ML",
                "iso3"       => "MLI",
                "phone_code" => "223",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/ml.svg",
            ],
            [
                "nombre"     => "Malta",
                "name"       => "Malta",
                "nom"        => "Malte",
                "iso2"       => "MT",
                "iso3"       => "MLT",
                "phone_code" => "356",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/mt.svg",
            ],
            [
                "nombre"     => "Marruecos",
                "name"       => "Morocco",
                "nom"        => "Maroc",
                "iso2"       => "MA",
                "iso3"       => "MAR",
                "phone_code" => "212",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/ma.svg",
            ],
            [
                "nombre"     => "Martinica",
                "name"       => "Martinique",
                "nom"        => "Martinique",
                "iso2"       => "MQ",
                "iso3"       => "MTQ",
                "phone_code" => "",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/mq.svg",
            ],
            [
                "nombre"     => "Mauricio",
                "name"       => "Mauritius",
                "nom"        => "Iles Maurice",
                "iso2"       => "MU",
                "iso3"       => "MUS",
                "phone_code" => "230",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/mu.svg",
            ],
            [
                "nombre"     => "Mauritania",
                "name"       => "Mauritania",
                "nom"        => "Mauritanie",
                "iso2"       => "MR",
                "iso3"       => "MRT",
                "phone_code" => "222",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/mr.svg",
            ],
            [
                "nombre"     => "Mayotte",
                "name"       => "Mayotte",
                "nom"        => "Mayotte",
                "iso2"       => "YT",
                "iso3"       => "MYT",
                "phone_code" => "262",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/yt.svg",
            ],
            [
                "nombre"     => "Micronesia",
                "name"       => "Estados Federados de",
                "nom"        => "Federados Estados de",
                "iso2"       => "FM",
                "iso3"       => "FSM",
                "phone_code" => "691",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/fm.svg",
            ],
            [
                "nombre"     => "Moldavia",
                "name"       => "Moldova",
                "nom"        => "Moldavie",
                "iso2"       => "MD",
                "iso3"       => "MDA",
                "phone_code" => "373",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/md.svg",
            ],
            [
                "nombre"     => "Mongolia",
                "name"       => "Mongolia",
                "nom"        => "Mongolie",
                "iso2"       => "MN",
                "iso3"       => "MNG",
                "phone_code" => "976",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/mn.svg",
            ],
            [
                "nombre"     => "Montenegro",
                "name"       => "Montenegro",
                "nom"        => "Monténégro",
                "iso2"       => "ME",
                "iso3"       => "MNE",
                "phone_code" => "382",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/me.svg",
            ],
            [
                "nombre"     => "Montserrat",
                "name"       => "Montserrat",
                "nom"        => "Montserrat",
                "iso2"       => "MS",
                "iso3"       => "MSR",
                "phone_code" => "1 664",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/ms.svg",
            ],
            [
                "nombre"     => "Mozambique",
                "name"       => "Mozambique",
                "nom"        => "Mozambique",
                "iso2"       => "MZ",
                "iso3"       => "MOZ",
                "phone_code" => "258",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/mz.svg",
            ],
            [
                "nombre"     => "Namibia",
                "name"       => "Namibia",
                "nom"        => "Namibie",
                "iso2"       => "NA",
                "iso3"       => "NAM",
                "phone_code" => "264",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/na.svg",
            ],
            [
                "nombre"     => "Nauru",
                "name"       => "Nauru",
                "nom"        => "Nauru",
                "iso2"       => "NR",
                "iso3"       => "NRU",
                "phone_code" => "674",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/nr.svg",
            ],
            [
                "nombre"     => "Nepal",
                "name"       => "Nepal",
                "nom"        => "Népal",
                "iso2"       => "NP",
                "iso3"       => "NPL",
                "phone_code" => "977",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/np.svg",
            ],
            [
                "nombre"     => "Nicaragua",
                "name"       => "Nicaragua",
                "nom"        => "Nicaragua",
                "iso2"       => "NI",
                "iso3"       => "NIC",
                "phone_code" => "505",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/ni.svg",
            ],
            [
                "nombre"     => "Niger",
                "name"       => "Niger",
                "nom"        => "Niger",
                "iso2"       => "NE",
                "iso3"       => "NER",
                "phone_code" => "227",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/ne.svg",
            ],
            [
                "nombre"     => "Nigeria",
                "name"       => "Nigeria",
                "nom"        => "Nigeria",
                "iso2"       => "NG",
                "iso3"       => "NGA",
                "phone_code" => "234",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/ng.svg",
            ],
            [
                "nombre"     => "Niue",
                "name"       => "Niue",
                "nom"        => "Niou",
                "iso2"       => "NU",
                "iso3"       => "NIU",
                "phone_code" => "683",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/nu.svg",
            ],
            [
                "nombre"     => "Noruega",
                "name"       => "Norway",
                "nom"        => "Norvège",
                "iso2"       => "NO",
                "iso3"       => "NOR",
                "phone_code" => "47",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/no.svg",
            ],
            [
                "nombre"     => "Nueva Caledonia",
                "name"       => "New Caledonia",
                "nom"        => "Nouvelle-Calédonie",
                "iso2"       => "NC",
                "iso3"       => "NCL",
                "phone_code" => "687",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/nc.svg",
            ],
            [
                "nombre"     => "Nueva Zelanda",
                "name"       => "New Zealand",
                "nom"        => "Nouvelle-Zélande",
                "iso2"       => "NZ",
                "iso3"       => "NZL",
                "phone_code" => "64",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/nz.svg",
            ],
            [
                "nombre"     => "Omán",
                "name"       => "Oman",
                "nom"        => "Oman",
                "iso2"       => "OM",
                "iso3"       => "OMN",
                "phone_code" => "968",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/om.svg",
            ],
            [
                "nombre"     => "Países Bajos",
                "name"       => "Netherlands",
                "nom"        => "Pays-Bas",
                "iso2"       => "NL",
                "iso3"       => "NLD",
                "phone_code" => "31",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/nl.svg",
            ],
            [
                "nombre"     => "Pakistán",
                "name"       => "Pakistan",
                "nom"        => "Pakistan",
                "iso2"       => "PK",
                "iso3"       => "PAK",
                "phone_code" => "92",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/pk.svg",
            ],
            [
                "nombre"     => "Palau",
                "name"       => "Palau",
                "nom"        => "Palau",
                "iso2"       => "PW",
                "iso3"       => "PLW",
                "phone_code" => "680",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/pw.svg",
            ],
            [
                "nombre"     => "Palestina",
                "name"       => "Palestine",
                "nom"        => "La Palestine",
                "iso2"       => "PS",
                "iso3"       => "PSE",
                "phone_code" => "",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/ps.svg",
            ],
            [
                "nombre"     => "Panamá",
                "name"       => "Panama",
                "nom"        => "Panama",
                "iso2"       => "PA",
                "iso3"       => "PAN",
                "phone_code" => "507",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/pa.svg",
            ],
            [
                "nombre"     => "Papúa Nueva Guinea",
                "name"       => "Papua New Guinea",
                "nom"        => "Papouasie-Nouvelle-Guinée",
                "iso2"       => "PG",
                "iso3"       => "PNG",
                "phone_code" => "675",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/pg.svg",
            ],
            [
                "nombre"     => "Paraguay",
                "name"       => "Paraguay",
                "nom"        => "Paraguay",
                "iso2"       => "PY",
                "iso3"       => "PRY",
                "phone_code" => "595",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/py.svg",
            ],
            [
                "nombre"     => "Perú",
                "name"       => "Peru",
                "nom"        => "Pérou",
                "iso2"       => "PE",
                "iso3"       => "PER",
                "phone_code" => "51",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/pe.svg",
            ],
            [
                "nombre"     => "Polinesia Francesa",
                "name"       => "French Polynesia",
                "nom"        => "Polynésie française",
                "iso2"       => "PF",
                "iso3"       => "PYF",
                "phone_code" => "689",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/pf.svg",
            ],
            [
                "nombre"     => "Polonia",
                "name"       => "Poland",
                "nom"        => "Pologne",
                "iso2"       => "PL",
                "iso3"       => "POL",
                "phone_code" => "48",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/pl.svg",
            ],
            [
                "nombre"     => "Portugal",
                "name"       => "Portugal",
                "nom"        => "Portugal",
                "iso2"       => "PT",
                "iso3"       => "PRT",
                "phone_code" => "351",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/pt.svg",
            ],
            [
                "nombre"     => "Puerto Rico",
                "name"       => "Puerto Rico",
                "nom"        => "Porto Rico",
                "iso2"       => "PR",
                "iso3"       => "PRI",
                "phone_code" => "1",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/pr.svg",
            ],
            [
                "nombre"     => "Qatar",
                "name"       => "Qatar",
                "nom"        => "Qatar",
                "iso2"       => "QA",
                "iso3"       => "QAT",
                "phone_code" => "974",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/qa.svg",
            ],
            [
                "nombre"     => "Reino Unido",
                "name"       => "United Kingdom",
                "nom"        => "Royaume-Uni",
                "iso2"       => "GB",
                "iso3"       => "GBR",
                "phone_code" => "44",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/gb.svg",
            ],
            [
                "nombre"     => "República Centroafricana",
                "name"       => "Central African Republic",
                "nom"        => "République Centrafricaine",
                "iso2"       => "CF",
                "iso3"       => "CAF",
                "phone_code" => "236",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/cf.svg",
            ],
            [
                "nombre"     => "República Checa",
                "name"       => "Czech Republic",
                "nom"        => "République Tchèque",
                "iso2"       => "CZ",
                "iso3"       => "CZE",
                "phone_code" => "420",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/cz.svg",
            ],
            [
                "nombre"     => "República Dominicana",
                "name"       => "Dominican Republic",
                "nom"        => "République Dominicaine",
                "iso2"       => "DO",
                "iso3"       => "DOM",
                "phone_code" => "1 809",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/do.svg",
            ],
            [
                "nombre"     => "Reunión",
                "name"       => "Réunion",
                "nom"        => "Réunion",
                "iso2"       => "RE",
                "iso3"       => "REU",
                "phone_code" => "",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/re.svg",
            ],
            [
                "nombre"     => "Ruanda",
                "name"       => "Rwanda",
                "nom"        => "Rwanda",
                "iso2"       => "RW",
                "iso3"       => "RWA",
                "phone_code" => "250",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/rw.svg",
            ],
            [
                "nombre"     => "Rumanía",
                "name"       => "Romania",
                "nom"        => "Roumanie",
                "iso2"       => "RO",
                "iso3"       => "ROU",
                "phone_code" => "40",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/ro.svg",
            ],
            [
                "nombre"     => "Rusia",
                "name"       => "Russia",
                "nom"        => "La Russie",
                "iso2"       => "RU",
                "iso3"       => "RUS",
                "phone_code" => "7",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/ru.svg",
            ],
            [
                "nombre"     => "Sahara Occidental",
                "name"       => "Western Sahara",
                "nom"        => "Sahara Occidental",
                "iso2"       => "EH",
                "iso3"       => "ESH",
                "phone_code" => "",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/eh.svg",
            ],
            [
                "nombre"     => "Samoa",
                "name"       => "Samoa",
                "nom"        => "Samoa",
                "iso2"       => "WS",
                "iso3"       => "WSM",
                "phone_code" => "685",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/ws.svg",
            ],
            [
                "nombre"     => "Samoa Americana",
                "name"       => "American Samoa",
                "nom"        => "Les Samoa américaines",
                "iso2"       => "AS",
                "iso3"       => "ASM",
                "phone_code" => "1 684",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/as.svg",
            ],
            [
                "nombre"     => "San Bartolomé",
                "name"       => "Saint Barthélemy",
                "nom"        => "Saint-Barthélemy",
                "iso2"       => "BL",
                "iso3"       => "BLM",
                "phone_code" => "590",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/bl.svg",
            ],
            [
                "nombre"     => "San Cristóbal y Nieves",
                "name"       => "Saint Kitts and Nevis",
                "nom"        => "Saint Kitts et Nevis",
                "iso2"       => "KN",
                "iso3"       => "KNA",
                "phone_code" => "1 869",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/kn.svg",
            ],
            [
                "nombre"     => "San Marino",
                "name"       => "San Marino",
                "nom"        => "San Marino",
                "iso2"       => "SM",
                "iso3"       => "SMR",
                "phone_code" => "378",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/sm.svg",
            ],
            [
                "nombre"     => "San Martín (Francia)",
                "name"       => "Saint Martin (French part)",
                "nom"        => "Saint-Martin (partie française)",
                "iso2"       => "MF",
                "iso3"       => "MAF",
                "phone_code" => "1 599",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/mf.svg",
            ],
            [
                "nombre"     => "San Pedro y Miquelón",
                "name"       => "Saint Pierre and Miquelon",
                "nom"        => "Saint-Pierre-et-Miquelon",
                "iso2"       => "PM",
                "iso3"       => "SPM",
                "phone_code" => "508",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/pm.svg",
            ],
            [
                "nombre"     => "San Vicente y las Granadinas",
                "name"       => "Saint Vincent and the Grenadines",
                "nom"        => "Saint-Vincent et Grenadines",
                "iso2"       => "VC",
                "iso3"       => "VCT",
                "phone_code" => "1 784",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/vc.svg",
            ],
            [
                "nombre"     => "Santa Elena",
                "name"       => "Ascensión y Tristán de Acuña",
                "nom"        => "Ascensión y Tristan de Acuña",
                "iso2"       => "SH",
                "iso3"       => "SHN",
                "phone_code" => "290",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/sh.svg",
            ],
            [
                "nombre"     => "Santa Lucía",
                "name"       => "Saint Lucia",
                "nom"        => "Sainte-Lucie",
                "iso2"       => "LC",
                "iso3"       => "LCA",
                "phone_code" => "1 758",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/lc.svg",
            ],
            [
                "nombre"     => "Santo Tomé y Príncipe",
                "name"       => "Sao Tome and Principe",
                "nom"        => "Sao Tomé et Principe",
                "iso2"       => "ST",
                "iso3"       => "STP",
                "phone_code" => "239",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/st.svg",
            ],
            [
                "nombre"     => "Senegal",
                "name"       => "Senegal",
                "nom"        => "Sénégal",
                "iso2"       => "SN",
                "iso3"       => "SEN",
                "phone_code" => "221",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/sn.svg",
            ],
            [
                "nombre"     => "Serbia",
                "name"       => "Serbia",
                "nom"        => "Serbie",
                "iso2"       => "RS",
                "iso3"       => "SRB",
                "phone_code" => "381",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/rs.svg",
            ],
            [
                "nombre"     => "Seychelles",
                "name"       => "Seychelles",
                "nom"        => "Les Seychelles",
                "iso2"       => "SC",
                "iso3"       => "SYC",
                "phone_code" => "248",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/sc.svg",
            ],
            [
                "nombre"     => "Sierra Leona",
                "name"       => "Sierra Leone",
                "nom"        => "Sierra Leone",
                "iso2"       => "SL",
                "iso3"       => "SLE",
                "phone_code" => "232",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/sl.svg",
            ],
            [
                "nombre"     => "Singapur",
                "name"       => "Singapore",
                "nom"        => "Singapour",
                "iso2"       => "SG",
                "iso3"       => "SGP",
                "phone_code" => "65",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/sg.svg",
            ],
            [
                "nombre"     => "Siria",
                "name"       => "Syria",
                "nom"        => "Syrie",
                "iso2"       => "SY",
                "iso3"       => "SYR",
                "phone_code" => "963",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/sy.svg",
            ],
            [
                "nombre"     => "Somalia",
                "name"       => "Somalia",
                "nom"        => "Somalie",
                "iso2"       => "SO",
                "iso3"       => "SOM",
                "phone_code" => "252",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/so.svg",
            ],
            [
                "nombre"     => "Sri lanka",
                "name"       => "Sri Lanka",
                "nom"        => "Sri Lanka",
                "iso2"       => "LK",
                "iso3"       => "LKA",
                "phone_code" => "94",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/lk.svg",
            ],
            [
                "nombre"     => "Sudáfrica",
                "name"       => "South Africa",
                "nom"        => "Afrique du Sud",
                "iso2"       => "ZA",
                "iso3"       => "ZAF",
                "phone_code" => "27",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/za.svg",
            ],
            [
                "nombre"     => "Sudán",
                "name"       => "Sudan",
                "nom"        => "Soudan",
                "iso2"       => "SD",
                "iso3"       => "SDN",
                "phone_code" => "249",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/sd.svg",
            ],
            [
                "nombre"     => "Suecia",
                "name"       => "Sweden",
                "nom"        => "Suède",
                "iso2"       => "SE",
                "iso3"       => "SWE",
                "phone_code" => "46",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/se.svg",
            ],
            [
                "nombre"     => "Suiza",
                "name"       => "Switzerland",
                "nom"        => "Suisse",
                "iso2"       => "CH",
                "iso3"       => "CHE",
                "phone_code" => "41",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/ch.svg",
            ],
            [
                "nombre"     => "Surinám",
                "name"       => "Suriname",
                "nom"        => "Surinam",
                "iso2"       => "SR",
                "iso3"       => "SUR",
                "phone_code" => "597",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/sr.svg",
            ],
            [
                "nombre"     => "Svalbard y Jan Mayen",
                "name"       => "Svalbard and Jan Mayen",
                "nom"        => "Svalbard et Jan Mayen",
                "iso2"       => "SJ",
                "iso3"       => "SJM",
                "phone_code" => "",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/sj.svg",
            ],
            [
                "nombre"     => "Swazilandia",
                "name"       => "Swaziland",
                "nom"        => "Swaziland",
                "iso2"       => "SZ",
                "iso3"       => "SWZ",
                "phone_code" => "268",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/sz.svg",
            ],
            [
                "nombre"     => "Tadjikistán",
                "name"       => "Tajikistan",
                "nom"        => "Le Tadjikistan",
                "iso2"       => "TJ",
                "iso3"       => "TJK",
                "phone_code" => "992",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/tj.svg",
            ],
            [
                "nombre"     => "Tailandia",
                "name"       => "Thailand",
                "nom"        => "Thaïlande",
                "iso2"       => "TH",
                "iso3"       => "THA",
                "phone_code" => "66",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/th.svg",
            ],
            [
                "nombre"     => "Taiwán",
                "name"       => "Taiwan",
                "nom"        => "Taiwan",
                "iso2"       => "TW",
                "iso3"       => "TWN",
                "phone_code" => "886",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/tw.svg",
            ],
            [
                "nombre"     => "Tanzania",
                "name"       => "Tanzania",
                "nom"        => "Tanzanie",
                "iso2"       => "TZ",
                "iso3"       => "TZA",
                "phone_code" => "255",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/tz.svg",
            ],
            [
                "nombre"     => "Territorio Británico del Océano Índico",
                "name"       => "British Indian Ocean Territory",
                "nom"        => "Territoire britannique de l'océan Indien",
                "iso2"       => "IO",
                "iso3"       => "IOT",
                "phone_code" => "",
                "continente" => "",
                "flag"       => "https://flagcdn.com/io.svg",
            ],
            [
                "nombre"     => "Territorios Australes y Antárticas Franceses",
                "name"       => "French Southern Territories",
                "nom"        => "Terres australes françaises",
                "iso2"       => "TF",
                "iso3"       => "ATF",
                "phone_code" => "",
                "continente" => "",
                "flag"       => "https://flagcdn.com/tf.svg",
            ],
            [
                "nombre"     => "Timor Oriental",
                "name"       => "East Timor",
                "nom"        => "Timor-Oriental",
                "iso2"       => "TL",
                "iso3"       => "TLS",
                "phone_code" => "670",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/tl.svg",
            ],
            [
                "nombre"     => "Togo",
                "name"       => "Togo",
                "nom"        => "Togo",
                "iso2"       => "TG",
                "iso3"       => "TGO",
                "phone_code" => "228",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/tg.svg",
            ],
            [
                "nombre"     => "Tokelau",
                "name"       => "Tokelau",
                "nom"        => "Tokélaou",
                "iso2"       => "TK",
                "iso3"       => "TKL",
                "phone_code" => "690",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/tk.svg",
            ],
            [
                "nombre"     => "Tonga",
                "name"       => "Tonga",
                "nom"        => "Tonga",
                "iso2"       => "TO",
                "iso3"       => "TON",
                "phone_code" => "676",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/to.svg",
            ],
            [
                "nombre"     => "Trinidad y Tobago",
                "name"       => "Trinidad and Tobago",
                "nom"        => "Trinidad et Tobago",
                "iso2"       => "TT",
                "iso3"       => "TTO",
                "phone_code" => "1 868",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/tt.svg",
            ],
            [
                "nombre"     => "Tunez",
                "name"       => "Tunisia",
                "nom"        => "Tunisie",
                "iso2"       => "TN",
                "iso3"       => "TUN",
                "phone_code" => "216",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/tn.svg",
            ],
            [
                "nombre"     => "Turkmenistán",
                "name"       => "Turkmenistan",
                "nom"        => "Le Turkménistan",
                "iso2"       => "TM",
                "iso3"       => "TKM",
                "phone_code" => "993",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/tm.svg",
            ],
            [
                "nombre"     => "Turquía",
                "name"       => "Turkey",
                "nom"        => "Turquie",
                "iso2"       => "TR",
                "iso3"       => "TUR",
                "phone_code" => "90",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/tr.svg",
            ],
            [
                "nombre"     => "Tuvalu",
                "name"       => "Tuvalu",
                "nom"        => "Tuvalu",
                "iso2"       => "TV",
                "iso3"       => "TUV",
                "phone_code" => "688",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/tv.svg",
            ],
            [
                "nombre"     => "Ucrania",
                "name"       => "Ukraine",
                "nom"        => "L'Ukraine",
                "iso2"       => "UA",
                "iso3"       => "UKR",
                "phone_code" => "380",
                "continente" => "Europa",
                "flag"       => "https://flagcdn.com/ua.svg",
            ],
            [
                "nombre"     => "Uganda",
                "name"       => "Uganda",
                "nom"        => "Ouganda",
                "iso2"       => "UG",
                "iso3"       => "UGA",
                "phone_code" => "256",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/ug.svg",
            ],
            [
                "nombre"     => "Uruguay",
                "name"       => "Uruguay",
                "nom"        => "Uruguay",
                "iso2"       => "UY",
                "iso3"       => "URY",
                "phone_code" => "598",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/uy.svg",
            ],
            [
                "nombre"     => "Uzbekistán",
                "name"       => "Uzbekistan",
                "nom"        => "L'Ouzbékistan",
                "iso2"       => "UZ",
                "iso3"       => "UZB",
                "phone_code" => "998",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/uz.svg",
            ],
            [
                "nombre"     => "Vanuatu",
                "name"       => "Vanuatu",
                "nom"        => "Vanuatu",
                "iso2"       => "VU",
                "iso3"       => "VUT",
                "phone_code" => "678",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/vu.svg",
            ],
            [
                "nombre"     => "Venezuela",
                "name"       => "Venezuela",
                "nom"        => "Venezuela",
                "iso2"       => "VE",
                "iso3"       => "VEN",
                "phone_code" => "58",
                "continente" => "América",
                "flag"       => "https://flagcdn.com/ve.svg",
            ],
            [
                "nombre"     => "Vietnam",
                "name"       => "Vietnam",
                "nom"        => "Vietnam",
                "iso2"       => "VN",
                "iso3"       => "VNM",
                "phone_code" => "84",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/vn.svg",
            ],
            [
                "nombre"     => "Wallis y Futuna",
                "name"       => "Wallis and Futuna",
                "nom"        => "Wallis et Futuna",
                "iso2"       => "WF",
                "iso3"       => "WLF",
                "phone_code" => "681",
                "continente" => "Australia y Oceanía",
                "flag"       => "https://flagcdn.com/wf.svg",
            ],
            [
                "nombre"     => "Yemen",
                "name"       => "Yemen",
                "nom"        => "Yémen",
                "iso2"       => "YE",
                "iso3"       => "YEM",
                "phone_code" => "967",
                "continente" => "Asia",
                "flag"       => "https://flagcdn.com/ye.svg",
            ],
            [
                "nombre"     => "Yibuti",
                "name"       => "Djibouti",
                "nom"        => "Djibouti",
                "iso2"       => "DJ",
                "iso3"       => "DJI",
                "phone_code" => "253",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/dj.svg",
            ],
            [
                "nombre"     => "Zambia",
                "name"       => "Zambia",
                "nom"        => "Zambie",
                "iso2"       => "ZM",
                "iso3"       => "ZMB",
                "phone_code" => "260",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/zm.svg",
            ],
            [
                "nombre"     => "Zimbabue",
                "name"       => "Zimbabwe",
                "nom"        => "Zimbabwe",
                "iso2"       => "ZW",
                "iso3"       => "ZWE",
                "phone_code" => "263",
                "continente" => "África",
                "flag"       => "https://flagcdn.com/zw.svg",
            ],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
